update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -17,17 +17,33 @@ env:
   TELEGRAM_UPDATE_PHOTO_CMD: telegram_update_photo.sh
 
 jobs:
-  check-input:
+  check_input:
     runs-on: ubuntu-latest
     steps:
       - name: Check input
         id: check_input
         run: |
           [[ ${{ github.event.inputs.version }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] && echo "match=true" >> $GITHUB_OUTPUT || echo "match=false" >> $GITHUB_OUTPUT
-      - name: Validate input
-        if: steps.check_input.outputs.match != 'true'
+#      - name: Validate input
+#        if: steps.check_input.outputs.match != 'true'
+#        run: |
+#          echo "::error::Incorrect release version format: ${{ github.event.inputs.version }}. Expected format: x.y.z."
+#          exit 1
+
+  create_tag:
+    runs-on: ubuntu-latest
+    needs: [ check_input ]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Check tag
+        id: check_tag
         run: |
-          echo "::error::Incorrect release version format: ${{ github.event.inputs.version }}. Expected format: x.y.z."
+          [[ $(git tag) =~ ${{ env.TAG }} ]] && echo "match=true" >> $GITHUB_OUTPUT || echo "match=false" >> $GITHUB_OUTPUT
+      - name: Validate tag
+        if: steps.create_tag.outputs.match == 'true'
+        run: |
+          echo "::error::Tag ${{ env.TAG }} already exists!"
           exit 1
 #  check-tag:
 #    runs-on: ubuntu-latest
